#!/usr/bin/env python3
"""Flatten src/icons/*.svg (Lucide) into src/qml/ui/Icons.qml.

Icon.qml bakes the stroke colour into a data URI at runtime, so only the
inner geometry of each SVG is kept — the outer <svg> element (size, stroke
attributes) is re-emitted by Icon.qml.
"""
import pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
src = root / "src" / "icons"
out = root / "src" / "qml" / "OmaRaw" / "Ui" / "Icons.qml"
shapes = {}
for f in sorted(src.glob("*.svg")):
    s = f.read_text()
    m = re.search(r"<svg[^>]*>(.*)</svg>", s, re.S)
    if not m:
        sys.exit(f"{f}: no <svg> element")
    inner = re.sub(r"\s+", " ", m.group(1)).strip()
    inner = re.sub(r"> <", "><", inner)
    inner = re.sub(r"<!--.*?-->", "", inner)
    shapes[f.stem] = inner
lines = ["pragma Singleton", "", "import QtQuick", "",
         "// Icon geometry, vendored from Lucide (ISC — see src/icons/LICENSE.lucide).",
         "// Path data rather than SVG files so Icon can bake the stroke colour into a",
         "// data URI: that tints without a shader, which the offscreen renderer used",
         "// for --shot and the tests does not provide.",
         "//",
         "// Generated by tools/gen-icons.py — do not hand-edit.",
         "QtObject {", "    readonly property var shapes: ({"]
items = list(shapes.items())
for i, (k, v) in enumerate(items):
    v = v.replace("'", "\\'")
    lines.append(f"        \"{k}\": '{v}'" + ("," if i < len(items) - 1 else ""))
lines += ["    })", "}", ""]
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(shapes)} icons)")
